version: '3.7'

services:
  zindagiapp:
    image: ghcr.io/zindagiapp/blazor:latest
    container_name: zindagi
    restart: unless-stopped
    environment:
      ASPNETCORE_ENVIRONMENT: ${APP_ENV}
      AUTH0__DOMAIN: ${APP_AUTH0_DOMAIN}
      AUTH0__CLIENTID: ${APP_AUTH0_CLIENTID}
      AUTH0__CLIENTSECRET: ${APP_AUTH0_CLIENTSECRET}
      SMTP__DISABLE: ${APP_SMTP_DISABLE}
      SMTP__FROM: ${APP_SMTP_FROM}
      SMTP__HOST: ${APP_SMTP_HOST}
      SMTP__PORT: ${APP_SMTP_PORT}
      SMTP__USERNAME: ${APP_SMTP_USERNAME}
      SMTP__PASSWORD: ${APP_SMTP_PASSWORD}
      SMTP__USESSL: ${APP_SMTP_USESSL}
      CONNECTIONSTRINGS__REDIS: ${APP_REDIS_CONNECTIONSTRING}
    volumes:
      - ./persistence/zindagi/logs:/app/logs
    networks:
      - default
    ports:
      - 80:80

networks:
  default:
    name: network_default
    driver: bridge
